export const PATH = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  RESET_PASSWORD: "/reset",
  DASHBOARD: "/dashboard",
  FEATURES: "/features",
  HOW_IT_WORKS: "/how-it-works",
  ABOUT: "/about",
  CONTACT: "/contact",
  STATS: "/stats",
  HOME: "/",
  ERROR: "*",
  ADMIN:"admin",
  ADMIN_OVERVIEW: "/admin/overview",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_EMPLOYEES: "/admin/employees",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_ATTENDANCE: "/admin/attendance",
  ADMIN_STAFF: "/admin/staff",
};
